src/content/models.py
from datetime import datetime
import os
import random
import string
from PIL import Image
import numpy as np
import pyclamd
import copy
from src import app, db
from src.utils import scan_file

class Tweet(db.Model):

	__tablename__ = "tweets"

	id = db.Column(db.Integer, primary_key=True)
	text = db.Column(db.String(140), nullable=False)
	created_at = db.Column(db.DateTime, nullable=False)
	img = db.Column(db.String(20), nullable=True)
	user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False) 
	is_signed = db.Column(db.Boolean, nullable=False, default=False)
	signature = db.Column(db.String, nullable=True)
	hashed_value = db.Column(db.String, nullable=True)

	def __init__(self, text, user_id, img, is_signed, signature, hashed_value):
		self.text = text
		self.user_id = user_id
		self.created_at = datetime.now()
		self.is_signed = is_signed
		self.signature = signature
		self.hashed_value = hashed_value
		if img:
			scan_file(img)
			result = Image.open(img)
			dir = os.path.join("src", app.config['UPLOAD_FOLDER'])
			filename = self._generate_unique_filename(dir)
			result.save(os.path.join(dir, filename))
			self.img = filename


	def __repr__(self):
		return f"<tweet {self.id} by {self.user_id}>"
	
	def _generate_unique_filename(self, directory):
		while True:
			filename = self._random_filename()+".jpg"
			full_path = os.path.join(directory, filename)
			if not os.path.exists(full_path):
				return filename
			
	def _random_filename(self):
		return ''.join(random.choices(string.ascii_letters + string.digits, k=16))
    

src/content/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileField, FileAllowed

class TweetForm(FlaskForm):
    text = TextAreaField("What's up?",validators=[DataRequired(),Length(min=1, max=140)])
    img = FileField('Include Image',validators=[FileAllowed(['jpg'], "Only .jpg files are allowed!")])
    private_key = FileField('Include private RSA key for signature:', validators=[FileAllowed(['pem'], "Only .pem files are allowed!")])

src/content/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from .forms import TweetForm
from .models import Tweet
from ..accounts.models import User
from src import db, limiter
from src.utils import confirmed_required
from sqlalchemy import desc
import bleach
from Crypto.PublicKey import RSA
from Crypto.Signature import pss
from Crypto.Hash import SHA512
from src.utils import scan_file

content_bp = Blueprint("content", __name__)
limiter.limit('10/second')(content_bp)

# bleach.sanitizer.ALLOWED_TAGS = frozenset({'a', 'abbr', 'acronym', 'b', 'blockquote', 'code', 'em', 'i', 'li', 'ol', 'strong', 'ul'})
# bleach.sanitizer.ALLOWED_ATTRIBUTES = {'a': ['href', 'title'], 'abbr': ['title'], 'acronym': ['title']}

WALL_URL = "content.wall"

@content_bp.route("/wall", methods=["GET", "POST"])
@login_required
@confirmed_required
def wall():
	form = TweetForm(request.form)
	if form.validate_on_submit():
		try:
			img = request.files['img'] if 'img' in request.files else None
			is_signed = False
			signature = None
			hashed_value = None
			try:
				private_key = request.files['private_key'] if 'private_key' in request.files else None
				scan_file(private_key)
				private_key.seek(0)
				priv_key = RSA.import_key(private_key.read())
				pub_key = RSA.import_key(current_user.pub_key)

				h = SHA512.new(str.encode(form.text.data))
				signature = pss.new(priv_key).sign(h)

				verifier = pss.new(pub_key)
				verifier.verify(h, signature)

				signature = signature.hex()
				hashed_value = str.encode(form.text.data).hex()
				is_signed = True
			except:
				is_signed = False

			tweet = Tweet(text=form.text.data, user_id=current_user.id, img=img, is_signed=is_signed, signature=signature, hashed_value=hashed_value)
			db.session.add(tweet)
			db.session.commit()

			flash("Your thought has been shared!", "success")
			return redirect(url_for(WALL_URL))
		except Exception:
			db.session.rollback()
			flash("Sharing failed. Please try again", "danger")

	page = request.args.get(key='page', default=1, type=int)
	tweets = Tweet.query.order_by(desc(Tweet.created_at)).paginate(page=page,per_page=12)
	for tweet in tweets.items:
		tweet.text = bleach.clean(tweet.text)
		tweet.author.username = bleach.clean(tweet.author.username)
		if tweet.hashed_value: tweet.hashed_value = bleach.clean(tweet.hashed_value)
		if tweet.signature: tweet.signature = bleach.clean(tweet.signature)
	username = bleach.clean(current_user.username)
	return render_template('content/wall.html', name=username, form=form, tweets=tweets)

@content_bp.route("/view_profile/<int:user_id>", methods=["GET", "POST"])
@login_required
@confirmed_required
def view_profile(user_id):
	user = User.query.filter_by(id=user_id).first()
	page = request.args.get('page', 1, type=int)
	user_tweets = Tweet.query.filter_by(user_id=user.id).order_by(desc(Tweet.created_at)).paginate(page=page,per_page=12)
	for tweet in user_tweets.items:
		tweet.text = bleach.clean(tweet.text)
		tweet.author.username = bleach.clean(tweet.author.username)
		if tweet.hashed_value: tweet.hashed_value = bleach.clean(tweet.hashed_value)
		if tweet.signature: tweet.signature = bleach.clean(tweet.signature)
	user.username = bleach.clean(user.username)
	user.pub_key = bleach.clean(user.pub_key.hex())
	return render_template('content/view_profile.html',user=user, tweets=user_tweets)

@content_bp.route("/")
@login_required
def home():
    return redirect(url_for(WALL_URL))

src/templates/content/view_profile.html
{% extends "_base.html" %}

{% block content %}

<h1 class="greeting"> @{{ user.username }}'s thoutghts:</h1>
<p class="text-muted small mb-0">
    <span class="fw-bold text-primary">Hex encoded public RSA key:</span>
    <a href="#" id="copy-key" data-key="{{ user.pub_key }}">Click to copy</a>
</p>
<p class="text-muted small mb-0">
    <span class="fw-bold text-primary">Profile created at:</span> {{ user.created_at.strftime('%Y-%m-%d %H:%M') }}
</p>

<div class="container my-4">
    <div class="row g-3">
        {% for row in tweets.items %}
            <div class="col-md-4">
                <div class="card shadow-sm h-100">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-2 d-flex justify-content-between align-items-center">
                            <h5 class="card-title mb-0">
                                <a href="{{ url_for('content.view_profile', user_id=row.author.id) }}">@{{ row.author.username }}</a>
                            </h5>
                            {% if row.is_signed %}
                                <span class="text-primary fw-bold me-2">Verified</span>
                            {% endif %}
                        </div>
                        <p class="text-muted small mb-0">
                            <span class="fw-bold text-primary">Posted on:</span> {{ row.created_at.strftime('%Y-%m-%d %H:%M') }}
                        </p>
						{% if row.is_signed %}
						<div>
						<p class="text-muted small mb-0">
							<span class="fw-bold text-primary">Hex encoded hashed(SHA512) value</span>
							<a href="#" id="copy-key" data-key="{{ row.hashed_value }}">Click to copy</a>
						</p>
						<p class="text-muted small mb-0">
							<span class="fw-bold text-primary">Hex encoded signature</span>
							<a href="#" id="copy-key" data-key="{{ row.signature }}">Click to copy</a>
						</p>
						</div>
						{% endif %}
                        <hr>
                        {% if row.img %}
                        <div class="mb-2 text-center">
                            <img src="{{ url_for('static', filename='uploads/' ~ row.img) }}" class="img-fluid display-image" alt="Tweet image">
                        </div>
                        {% endif %}
                        <p class="card-text flex-grow-1">{{ row.text | safe }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<nav aria-label="Tweet pagination">
    <ul class="pagination justify-content-center my-4">
        {% for page_num in tweets.iter_pages(left_edge=2, right_edge=2, left_current=1, right_current=2) %}
            {% if page_num %}
                <li class="page-item {% if tweets.page == page_num %}active{% endif %}">
                    <a class="page-link" href="{{ url_for('content.wall', page=page_num) }}">{{ page_num }}</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">...</span>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</nav>

{% endblock %}

src/templates/content/wall.html
{% extends "_base.html" %}

{% block content %}

<h1 class="greeting">Welcome @{{ name }}!</h1>

<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
    	<main class="form-signin w-100 m-auto">
      		<form role="form" method="post" action="" enctype="multipart/form-data">
				{{ form.csrf_token }} 
				{#  
					Inserts a hidden input field in the HTML form containing 
					a unique, secret, and unpredictable value generated by the server.
					When the form is submitted, Flask-WTF verifies the CSRF token against 
					the token stored in the user's session
				#}

				<h1 class="h3 mb-3 fw-normal text-center"> Your safespace </h1>

				<div class="form-floating">
				{{ form.text(placeholder="Your thoughts", class="form-control mb-2 display-text", rows="5") }}
				{{ form.text.label }}
					{% if form.text.errors %}
						{% for error in form.text.errors %}
							<div class="alert alert-danger" role="alert">
								{{ error }}
							</div>
						{% endfor %}
					{% endif %}
				</div>
				<p class="fw-bold " >Add an image</p>
                <div class="form-group mb-3">
                    {{ form.img(class="form-control") }}
                    {% if form.img.errors %}
                        {% for error in form.img.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
				<p class="fw-bold" >Sign your thought</p>
				<div class="form-group mb-3">
					{{ form.private_key(placeholder="Private RSA key", class="form-control") }}
					{% if form.private_key.errors %}
						{% for error in form.private_key.errors %}
							<div class="alert alert-danger" role="alert">
								{{ error }}
							</div>
						{% endfor %}
					{% endif %}
				</div>

        		<button class="w-100 btn btn-lg btn-primary" type="submit">Share</button>
      		</form>
    	</main>
	</div>
	<div class="col-md-4"></div>
</div>

<div class="container my-4">
    <div class="row g-3">
        {% for row in tweets.items %}
            <div class="col-md-4">
                <div class="card shadow-sm h-100">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-2 d-flex justify-content-between align-items-center">
                            <h5 class="card-title mb-0">
                                <a href="{{ url_for('content.view_profile', user_id=row.author.id) }}">@{{ row.author.username }}</a>
                            </h5>
                            {% if row.is_signed %}
                                <span class="text-primary fw-bold me-2">Verified</span>
                            {% endif %}
                        </div>
                        <p class="text-muted small mb-0">
                            <span class="fw-bold text-primary">Posted on:</span> {{ row.created_at.strftime('%Y-%m-%d %H:%M') }}
                        </p>
						{% if row.is_signed %}
						<div>
						<p class="text-muted small mb-0">
							<span class="fw-bold text-primary">Hex encoded hashed(SHA512) value</span>
							<a href="#" id="copy-key" data-key="{{ row.hashed_value }}">Click to copy</a>
						</p>
						<p class="text-muted small mb-0">
							<span class="fw-bold text-primary">Hex encoded signature</span>
							<a href="#" id="copy-key" data-key="{{ row.signature }}">Click to copy</a>
						</p>
						</div>
						{% endif %}
                        <hr>
                        {% if row.img %}
                        <div class="mb-2 text-center">
                            <img src="{{ url_for('static', filename='uploads/' ~ row.img) }}" class="img-fluid display-image" alt="Tweet image">
                        </div>
                        {% endif %}
                        <p class="card-text flex-grow-1">{{ row.text | safe }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<nav aria-label="Tweet pagination">
    <ul class="pagination justify-content-center my-4">
        {% for page_num in tweets.iter_pages(left_edge=2, right_edge=2, left_current=1, right_current=2) %}
            {% if page_num %}
                <li class="page-item {% if tweets.page == page_num %}active{% endif %}">
                    <a class="page-link" href="{{ url_for('content.wall', page=page_num) }}">{{ page_num }}</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">...</span>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</nav>

{% endblock %}